package taskmanager

import (
	"bufio"
	"context"
	"fmt"
	"net"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"runtime"
	"sort"
	"strconv"
	"strings"
	"time"
)

const linuxToolsActionTimeout = 2 * time.Minute

var hostnameLabelPattern = regexp.MustCompile(`^[A-Za-z0-9]([A-Za-z0-9-]{0,61}[A-Za-z0-9])?$`)

type LinuxToolsSnapshot struct {
	Platform   string      `json:"platform"`
	Supported  bool        `json:"supported"`
	Timezone   string      `json:"timezone,omitempty"`
	Timezones  []string    `json:"timezones"`
	Hostname   string      `json:"hostname,omitempty"`
	DNSServers []string    `json:"dns_servers"`
	DNSSource  string      `json:"dns_source,omitempty"`
	Swap       SwapSummary `json:"swap"`
	Notices    []string    `json:"notices,omitempty"`
}

type SwapSummary struct {
	TotalBytes uint64       `json:"total_bytes"`
	UsedBytes  uint64       `json:"used_bytes"`
	FreeBytes  uint64       `json:"free_bytes"`
	Devices    []SwapDevice `json:"devices"`
}

type SwapDevice struct {
	Filename  string `json:"filename"`
	Type      string `json:"type"`
	SizeBytes uint64 `json:"size_bytes"`
	UsedBytes uint64 `json:"used_bytes"`
	Priority  string `json:"priority"`
}

func (s *Service) LinuxTools(ctx context.Context) LinuxToolsSnapshot {
	snapshot := LinuxToolsSnapshot{
		Platform:   runtime.GOOS,
		Supported:  runtime.GOOS == "linux",
		Timezones:  []string{},
		DNSServers: []string{},
		Swap: SwapSummary{
			Devices: []SwapDevice{},
		},
	}
	if !snapshot.Supported {
		snapshot.Notices = append(snapshot.Notices, fmt.Sprintf("Linux tools are unavailable on %s.", runtime.GOOS))
		return snapshot
	}

	var err error
	if snapshot.Hostname, err = os.Hostname(); err != nil {
		snapshot.Notices = append(snapshot.Notices, fmt.Sprintf("read hostname: %v", err))
	}
	if snapshot.Timezone, err = currentTimezone(ctx); err != nil {
		snapshot.Notices = append(snapshot.Notices, err.Error())
	}
	if snapshot.Timezones, err = listTimezones(); err != nil {
		snapshot.Notices = append(snapshot.Notices, err.Error())
	}
	if snapshot.DNSServers, snapshot.DNSSource, err = readDNSServers("/etc/resolv.conf"); err != nil {
		snapshot.Notices = append(snapshot.Notices, err.Error())
	}
	if snapshot.Swap, err = readSwapSummary(); err != nil {
		snapshot.Notices = append(snapshot.Notices, err.Error())
	}

	return snapshot
}

func (s *Service) SetTimezone(ctx context.Context, timezone string) error {
	timezone = strings.TrimSpace(timezone)
	if err := validateLinux(); err != nil {
		return err
	}
	if err := validateTimezone(timezone); err != nil {
		return err
	}
	return runLinuxToolCommand(ctx, "timedatectl", "set-timezone", timezone)
}

func (s *Service) SetHostname(ctx context.Context, hostname string) error {
	hostname = strings.TrimSpace(hostname)
	if err := validateLinux(); err != nil {
		return err
	}
	if err := validateHostname(hostname); err != nil {
		return err
	}
	return runLinuxToolCommand(ctx, "hostnamectl", "set-hostname", hostname)
}

func (s *Service) SetDNS(ctx context.Context, servers []string) error {
	if err := validateLinux(); err != nil {
		return err
	}

	cleanServers, err := normalizeDNSServers(servers)
	if err != nil {
		return err
	}

	content := "# Generated by FlowPanel Linux Tools.\n"
	for _, server := range cleanServers {
		content += "nameserver " + server + "\n"
	}

	return os.WriteFile("/etc/resolv.conf", []byte(content), 0644)
}

func (s *Service) ResizeSwap(ctx context.Context, sizeMB int) error {
	if err := validateLinux(); err != nil {
		return err
	}
	if sizeMB < 64 || sizeMB > 1048576 {
		return fmt.Errorf("swap size must be between 64 MB and 1048576 MB")
	}

	device, err := currentSwapFile()
	if err != nil {
		return err
	}
	path := device.Filename
	if _, err := os.Stat(path); err != nil {
		return fmt.Errorf("inspect swap file %s: %w", path, err)
	}

	if err := runLinuxToolCommand(ctx, "swapoff", path); err != nil {
		return err
	}
	enabled := false
	defer func() {
		if !enabled {
			_ = runLinuxToolCommand(context.Background(), "swapon", path)
		}
	}()

	if err := allocateSwapFile(ctx, path, sizeMB); err != nil {
		return err
	}
	if err := os.Chmod(path, 0600); err != nil {
		return fmt.Errorf("chmod swap file: %w", err)
	}
	if err := runLinuxToolCommand(ctx, "mkswap", path); err != nil {
		return err
	}
	if err := runLinuxToolCommand(ctx, "swapon", path); err != nil {
		return err
	}
	enabled = true

	return nil
}

func validateLinux() error {
	if runtime.GOOS != "linux" {
		return fmt.Errorf("Linux tools are unavailable on %s", runtime.GOOS)
	}
	return nil
}

func currentTimezone(ctx context.Context) (string, error) {
	if timedatectl, err := exec.LookPath("timedatectl"); err == nil {
		if output, err := runCommand(ctx, timedatectl, "show", "-p", "Timezone", "--value"); err == nil {
			if timezone := strings.TrimSpace(output); timezone != "" {
				return timezone, nil
			}
		}
	}

	target, err := os.Readlink("/etc/localtime")
	if err != nil {
		return "", fmt.Errorf("read timezone: %w", err)
	}
	if index := strings.Index(target, "/zoneinfo/"); index >= 0 {
		return strings.TrimPrefix(target[index:], "/zoneinfo/"), nil
	}
	return "", fmt.Errorf("read timezone: unsupported /etc/localtime target")
}

func validateTimezone(timezone string) error {
	if timezone == "" {
		return fmt.Errorf("timezone is required")
	}
	clean := filepath.Clean(timezone)
	if clean != timezone || filepath.IsAbs(timezone) || strings.HasPrefix(timezone, "..") || strings.Contains(timezone, "/../") {
		return fmt.Errorf("timezone must be a valid zoneinfo name")
	}

	info, err := os.Stat(filepath.Join("/usr/share/zoneinfo", timezone))
	if err != nil {
		return fmt.Errorf("timezone %q is not available", timezone)
	}
	if info.IsDir() {
		return fmt.Errorf("timezone %q is not a zone file", timezone)
	}
	return nil
}

func listTimezones() ([]string, error) {
	root := "/usr/share/zoneinfo"
	skipNames := map[string]struct{}{
		"iso3166.tab":       {},
		"leap-seconds.list": {},
		"leapseconds":       {},
		"localtime":         {},
		"posix":             {},
		"right":             {},
		"tzdata.zi":         {},
		"zone.tab":          {},
		"zone1970.tab":      {},
	}

	timezones := make([]string, 0, 450)
	err := filepath.WalkDir(root, func(path string, entry os.DirEntry, err error) error {
		if err != nil {
			return nil
		}
		if path == root {
			return nil
		}
		name := entry.Name()
		if _, skip := skipNames[name]; skip {
			if entry.IsDir() {
				return filepath.SkipDir
			}
			return nil
		}
		if entry.IsDir() {
			return nil
		}

		timezone, err := filepath.Rel(root, path)
		if err != nil || strings.Contains(timezone, ".") {
			return nil
		}
		timezones = append(timezones, filepath.ToSlash(timezone))
		return nil
	})
	if err != nil {
		return nil, fmt.Errorf("list timezones: %w", err)
	}

	sort.Strings(timezones)
	return timezones, nil
}

func validateHostname(hostname string) error {
	if len(hostname) == 0 || len(hostname) > 253 {
		return fmt.Errorf("hostname must be between 1 and 253 characters")
	}
	for _, label := range strings.Split(strings.TrimSuffix(hostname, "."), ".") {
		if !hostnameLabelPattern.MatchString(label) {
			return fmt.Errorf("hostname contains an invalid label")
		}
	}
	return nil
}

func readDNSServers(path string) ([]string, string, error) {
	file, err := os.Open(path)
	if err != nil {
		return []string{}, path, fmt.Errorf("read DNS servers: %w", err)
	}
	defer file.Close()

	servers := make([]string, 0, 2)
	scanner := bufio.NewScanner(file)
	for scanner.Scan() {
		fields := strings.Fields(scanner.Text())
		if len(fields) >= 2 && fields[0] == "nameserver" {
			servers = append(servers, fields[1])
		}
	}
	if err := scanner.Err(); err != nil {
		return servers, path, fmt.Errorf("read DNS servers: %w", err)
	}
	return servers, path, nil
}

func normalizeDNSServers(servers []string) ([]string, error) {
	seen := make(map[string]struct{})
	clean := make([]string, 0, len(servers))
	for _, server := range servers {
		server = strings.TrimSpace(server)
		if server == "" {
			continue
		}
		ip := net.ParseIP(server)
		if ip == nil {
			return nil, fmt.Errorf("%q is not a valid DNS server IP", server)
		}
		normalized := ip.String()
		if _, ok := seen[normalized]; ok {
			continue
		}
		seen[normalized] = struct{}{}
		clean = append(clean, normalized)
	}
	if len(clean) == 0 {
		return nil, fmt.Errorf("at least one DNS server is required")
	}
	return clean, nil
}

func readSwapSummary() (SwapSummary, error) {
	summary := SwapSummary{Devices: []SwapDevice{}}

	meminfo, err := os.ReadFile("/proc/meminfo")
	if err != nil {
		return summary, fmt.Errorf("read swap memory: %w", err)
	}
	values := parseMeminfoKiB(string(meminfo))
	summary.TotalBytes = values["SwapTotal"] * 1024
	summary.FreeBytes = values["SwapFree"] * 1024
	if summary.TotalBytes >= summary.FreeBytes {
		summary.UsedBytes = summary.TotalBytes - summary.FreeBytes
	}

	devices, err := parseSwapDevices("/proc/swaps")
	if err != nil {
		return summary, err
	}
	summary.Devices = devices
	return summary, nil
}

func parseMeminfoKiB(content string) map[string]uint64 {
	values := make(map[string]uint64)
	for _, line := range strings.Split(content, "\n") {
		fields := strings.Fields(line)
		if len(fields) < 2 {
			continue
		}
		value, err := strconv.ParseUint(fields[1], 10, 64)
		if err != nil {
			continue
		}
		values[strings.TrimSuffix(fields[0], ":")] = value
	}
	return values
}

func parseSwapDevices(path string) ([]SwapDevice, error) {
	content, err := os.ReadFile(path)
	if err != nil {
		return []SwapDevice{}, fmt.Errorf("read swap devices: %w", err)
	}

	lines := nonEmptyLines(string(content))
	devices := make([]SwapDevice, 0, len(lines))
	for _, line := range lines[1:] {
		fields := strings.Fields(line)
		if len(fields) < 5 {
			continue
		}
		sizeKiB, _ := strconv.ParseUint(fields[2], 10, 64)
		usedKiB, _ := strconv.ParseUint(fields[3], 10, 64)
		devices = append(devices, SwapDevice{
			Filename:  fields[0],
			Type:      fields[1],
			SizeBytes: sizeKiB * 1024,
			UsedBytes: usedKiB * 1024,
			Priority:  fields[4],
		})
	}

	return devices, nil
}

func currentSwapFile() (SwapDevice, error) {
	devices, err := parseSwapDevices("/proc/swaps")
	if err != nil {
		return SwapDevice{}, err
	}
	for _, device := range devices {
		if device.Type == "file" {
			return device, nil
		}
	}
	if len(devices) > 0 {
		return SwapDevice{}, fmt.Errorf("active swap is not a file and cannot be resized from FlowPanel")
	}
	return SwapDevice{}, fmt.Errorf("no active swap file is available to resize")
}

func allocateSwapFile(ctx context.Context, path string, sizeMB int) error {
	if _, err := exec.LookPath("fallocate"); err == nil {
		if err := runLinuxToolCommand(ctx, "fallocate", "-l", fmt.Sprintf("%dM", sizeMB), path); err == nil {
			return nil
		}
	}
	return runLinuxToolCommand(ctx, "dd", "if=/dev/zero", "of="+path, "bs=1M", fmt.Sprintf("count=%d", sizeMB), "status=none")
}

func runLinuxToolCommand(ctx context.Context, name string, args ...string) error {
	commandPath, err := exec.LookPath(name)
	if err != nil {
		return fmt.Errorf("%s is not available", name)
	}

	actionCtx, cancel := context.WithTimeout(ctx, linuxToolsActionTimeout)
	defer cancel()

	_, err = runCommand(actionCtx, commandPath, args...)
	return err
}
